---
roles:
  - name: forti-role
    src: https://github.com/balazsrakhely/forti-role

collections:
  - name: ansible.netcommon
    version: "7.2.0"
  - name: fortinet.fortimanager
    version: "2.10.0"